// ptero.js — Pterodactyl panel API wrapper
// Admin key (ptlc) for panel management: create/delete users, servers, nodes
// User client API keys (ptla_...) for direct server control — generated by
// each user from the panel (Account -> API Credentials), NOT via email/password.
// Pterodactyl has no email+password -> JWT login route on its public API.

const axios = require("axios");

const BASE = "https://panel.kryz-net.space/api";
const PANEL_URL = "https://panel.kryz-net.space";
// Prefer an env var so the key isn't hardcoded; falls back to the existing value.
const ADMIN_KEY = process.env.PTERO_ADMIN_KEY || "ptla_j9G9jiV9dsbmzxJCqyJyuZ0WHfvnrk2p3w9pjoEo46R";

const headers = (token) => ({ Authorization: `Bearer ${token}`, Accept: "application/json" });

// ---- CLIENT: list user's servers (validates a client API key works too) ----
async function listClientServers(clientKey) {
    const r = await axios.get(`${BASE}/client`, { headers: headers(clientKey), timeout: 15000, validateStatus: () => true });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed (${r.status})`);
    return (r.data?.data || []).map(s => ({
        id: s.attributes.uuid,
        identifier: s.attributes.identifier,
        name: s.attributes.name,
        description: s.attributes.description,
        suspended: s.attributes.suspended,
        limits: s.attributes.limits,
        relationships: s.attributes.relationships
    }));
}

// Get server power state
async function getServerState(clientKey, serverId) {
    const r = await axios.get(`${BASE}/client/servers/${serverId}/resources`, {
        headers: headers(clientKey), timeout: 15000, validateStatus: () => true
    });
    if (r.status !== 200) return { state: "unknown", status: r.status };
    const a = r.data?.attributes;
    return { state: a?.current_state, cpu: a?.resource_utilization?.cpu, ram: a?.resource_utilization?.memory, disk: a?.resource_utilization?.disk };
}

// Power control: start/stop/restart/kill
async function powerAction(clientKey, serverId, action) {
    const valid = ["start", "stop", "restart", "kill"];
    if (!valid.includes(action)) throw new Error(`Invalid action: ${action}. Use: ${valid.join(", ")}`);
    const r = await axios.post(`${BASE}/client/servers/${serverId}/power`, { signal: action }, {
        headers: headers(clientKey), timeout: 15000, validateStatus: () => true
    });
    if (r.status !== 204 && r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Power action failed (${r.status})`);
    return true;
}

// ---- ADMIN: list all users ----
async function listUsers() {
    const r = await axios.get(`${BASE}/application/users?per_page=100`, { headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed (${r.status})`);
    return (r.data?.data || []).map(u => ({
        id: u.attributes.id, email: u.attributes.email,
        name: `${u.attributes.first_name} ${u.attributes.last_name}`.trim(),
        admin: u.attributes.root_admin, suspended: u.attributes.server_owner
    }));
}

// ---- ADMIN: create user ----
async function createUser(email, username, firstName, lastName, password) {
    const r = await axios.post(`${BASE}/application/users`, {
        email, username, first_name: firstName, last_name: lastName || "", password: password || undefined
    }, { headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true });
    if (r.status !== 200 && r.status !== 201) throw new Error(r.data?.errors?.[0]?.detail || `Create failed (${r.status})`);
    return { id: r.data?.attributes?.id, email: r.data?.attributes?.email };
}

// ---- ADMIN: delete user ----
async function deleteUser(userId) {
    const r = await axios.delete(`${BASE}/application/users/${userId}`, { headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true });
    if (r.status !== 204) throw new Error(r.data?.errors?.[0]?.detail || `Delete failed (${r.status})`);
    return true;
}

// ---- ADMIN: list all servers ----
async function listServers() {
    const r = await axios.get(`${BASE}/application/servers?per_page=100`, { headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed (${r.status})`);
    return (r.data?.data || []).map(s => ({
        id: s.attributes.id, name: s.attributes.name, uuid: s.attributes.uuid,
        node: s.attributes.node, egg: s.attributes.egg, owner_id: s.attributes.owner_id,
        limits: s.attributes.limits
    }));
}

// ---- ADMIN: fetch an egg's docker image, startup command, and default env vars ----
async function getEgg(nestId, eggId) {
    const r = await axios.get(`${BASE}/application/nests/${nestId}/eggs/${eggId}?include=variables`, {
        headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true
    });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed to fetch egg ${eggId} in nest ${nestId} (${r.status})`);
    const attrs = r.data.attributes;
    const variables = (attrs.relationships?.variables?.data || []).map(v => ({
        name: v.attributes.env_variable,
        default: v.attributes.default_value
    }));
    return {
        id: attrs.id,
        name: attrs.name,
        docker_image: attrs.docker_image,
        startup: attrs.startup,
        variables
    };
}

// ---- ADMIN: find a free (unassigned) allocation on a node ----
async function getFreeAllocation(nodeId) {
    const r = await axios.get(`${BASE}/application/nodes/${nodeId}/allocations?per_page=100`, {
        headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true
    });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed to fetch allocations for node ${nodeId} (${r.status})`);
    const free = (r.data?.data || []).find(a => !a.attributes.assigned);
    if (!free) throw new Error(`No free allocation on node ${nodeId} — add one in the panel first.`);
    return free.attributes.id;
}

// ---- ADMIN: list nests (egg categories) ----
async function listNests() {
    const r = await axios.get(`${BASE}/application/nests?per_page=100`, { headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed (${r.status})`);
    return (r.data?.data || []).map(n => ({ id: n.attributes.id, name: n.attributes.name }));
}

// ---- ADMIN: list eggs under a nest ----
async function listEggs(nestId) {
    const r = await axios.get(`${BASE}/application/nests/${nestId}/eggs?per_page=100`, { headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed (${r.status})`);
    return (r.data?.data || []).map(e => ({ id: e.attributes.id, name: e.attributes.name }));
}

// ---- ADMIN: create server ----
// eggId + nodeId are required — Pterodactyl needs to know which image/startup
// command to run and which allocation (IP:port) to bind. Docker image, startup
// command, and environment defaults are pulled straight from the egg so you
// don't have to hand-specify them (and get them wrong for whatever egg it is).
async function createServer(name, ownerId, nestId, eggId, nodeId, memory, disk, cpu) {
    const egg = await getEgg(nestId, eggId);
    const allocationId = await getFreeAllocation(nodeId);

    const environment = {};
    for (const v of egg.variables) environment[v.name] = v.default ?? "";

    const r = await axios.post(`${BASE}/application/servers`, {
        name,
        user: ownerId,
        egg: egg.id,
        docker_image: egg.docker_image,
        startup: egg.startup,
        environment,
        limits: { memory: memory || 512, swap: 0, disk: disk || 1024, io: 500, cpu: cpu || 100 },
        feature_limits: { databases: 1, allocations: 1, backups: 1 },
        allocation: { default: allocationId }
    }, { headers: headers(ADMIN_KEY), timeout: 30000, validateStatus: () => true });
    if (r.status !== 200 && r.status !== 201) throw new Error(JSON.stringify(r.data?.errors || r.data).slice(0, 300));
    return { id: r.data?.attributes?.id, name: r.data?.attributes?.name, uuid: r.data?.attributes?.uuid };
}

// ---- ADMIN: delete server ----
async function deleteServer(serverId, force = false) {
    const r = await axios.delete(`${BASE}/application/servers/${serverId}${force ? "/force" : ""}`, {
        headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true
    });
    if (r.status !== 204) throw new Error(r.data?.errors?.[0]?.detail || `Delete failed (${r.status})`);
    return true;
}

// ---- ADMIN: list nodes ----
async function listNodes() {
    const r = await axios.get(`${BASE}/application/nodes?per_page=100`, { headers: headers(ADMIN_KEY), timeout: 15000, validateStatus: () => true });
    if (r.status !== 200) throw new Error(r.data?.errors?.[0]?.detail || `Failed (${r.status})`);
    return (r.data?.data || []).map(n => ({
        id: n.attributes.id, name: n.attributes.name, fqdn: n.attributes.fqdn,
        memory: n.attributes.memory, memory_overallocate: n.attributes.memory_overallocate,
        disk: n.attributes.disk, daemon_listen: n.attributes.daemon_listen
    }));
}

// ---- ADMIN: get user by email ----
async function getUserByEmail(email) {
    const users = await listUsers();
    return users.find(u => u.email.toLowerCase() === email.toLowerCase()) || null;
}

module.exports = {
    listClientServers, getServerState, powerAction,
    listUsers, createUser, deleteUser,
    listServers, createServer, deleteServer,
    listNodes, listNests, listEggs, getUserByEmail,
    PANEL_URL
};
